
---
paths:
  only:
    - test/language
  skip:
    - test/annexB
    - test/language/expressions
features:
  filter:
    - async-iteration
    - generators
  skip:
    - SharedArrayBuffer
    - BigInt
