
---
skip:
  paths:
    - test/annexB
    - test/language/expressions
  features:
    - SharedArrayBuffer
    - BigInt
  files:
    - test/language/module-code/privatename-not-valid-earlyerr-module-1.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-2.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-3.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-4.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-5.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-6.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-7.js
    - test/language/module-code/privatename-not-valid-earlyerr-module-8.js
